runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: andysite-d9eed:us-central1:andy-site-db
env_variables:
  DB_USER: hapi-server
  DB_PASS: abc1234!
  DB_NAME: andy-site
  DB_SOCKET: /cloudsql/andysite-d9eed:us-central1:andy-site-db